/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Test;
import org.ruben.annotationUser.Person;
import org.ruben.annotationUser.PersonBuilder;
import static org.junit.Assert.*;

public class AppTest {


    @Test 
    public void given_annotation_when_PersonBuilder_then_ok() {
        Person person = new PersonBuilder().setAge(25).setName("Raul").build();
        Person person1 = new Person();
        person1.setName("Raul");
        person1.setAge(25);
        assertEquals(person, person1);
    }
}
